"""add_board_combination_and_game

Revision ID: ff5a22597a1f
Revises: 
Create Date: 2020-03-28 20:19:53.654489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff5a22597a1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_combination',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('letters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('found_words', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('board_combination_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['board_combination_id'], ['board_combination.id'], name='board_combination_id', onupdate='CASCADE', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('board_combination')
    # ### end Alembic commands ###
