
class ErrorCodes:
    COMBINATION_DOES_NOT_EXIST = 'COMBINATION_DOES_NOT_EXIST'
    GAME_DOES_NOT_EXIST = 'GAME_DOES_NOT_EXIST'
    GAME_IS_FINISHED = 'GAME_IS_FINISHED'
    WORD_HAS_BEEN_ADDED_ALREADY = 'WORD_HAS_BEEN_ADDED_ALREADY'

    INCORRECT_LENGTH = 'INCORRECT_LENGTH'
    INCORRECT_SEQUENCE = 'INCORRECT_SEQUENCE'
    WORD_DOES_NOT_EXIST = 'WORD_DOES_NOT_EXIST'
