version: '3'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=boggle
      - POSTGRES_PASSWORD=boggle
      - POSTGRES_DB=boggle
    volumes:
      - /var/lib/postgresql/data/
  backend:
    image: boggle-backend:latest
    build:
      context: ${PWD-.}/../../
      dockerfile: ${PWD-.}/../images/backend/Dockerfile
    environment:
      - APP_ENVIRONMENT_NAME=production
      - DB_CONNECTION_URL=postgresql://boggle:boggle@database:5432/boggle
    ports:
      - "8080:8080"
    depends_on:
      - database
  frontend:
    image: boggle-frontend:latest
    build:
      context: ${PWD-.}/../../
      dockerfile: ${PWD-.}/../images/frontend/Dockerfile
      args:
        apiBaseUrl: http://127.0.0.1/api/v1
        siteUrl: http://127.0.0.1/
    ports:
      - "3000:3000"
  nginx:
    image: boggle-nginx:latest
    build:
      context: ${PWD-.}/../../
      dockerfile: ${PWD-.}/../images/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend