version: '3'
services:
  backend:
    image: boggle-backend:latest
    build:
      context: ${PWD-.}/../../
      dockerfile: ${PWD-.}/../images/backend/Dockerfile
    environment:
      - GUNICORN_CMD_ARGS="--reload"
    volumes:
      - ${PWD-.}/../../src/backend/:/app/
    ports:
      - "8080:8080"
  frontend:
    image: boggle-frontend:latest
    build:
      context: ${PWD-.}/../../
      dockerfile: ${PWD-.}/../images/frontend/Dockerfile
      args:
        apiBaseUrl: http://127.0.0.1:8080/api/v1
        siteUrl: http://127.0.0.1:3000/
    command: ["yarn", "start"]
    stdin_open: true
    volumes:
      - ${PWD-.}/../../src/frontend/:/app/
      - /app/node_modules
    ports:
      - "3000:3000"