version: '3'
services:
  backend:
    image: boggle-backend:latest
    build:
      context: ${PWD-.}/../../
      dockerfile: ${PWD-.}/../images/backend/Dockerfile
    entrypoint: ["python", "-m", "unittest"]
    environment:
      - APP_ENVIRONMENT_NAME=test
    volumes:
      - ${PWD-.}/../../src/backend/:/app/
